'use client';

import { useState, useEffect, useCallback, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { DataSourceIndicator } from '@/components/DataSourceIndicator';
import {
  sampleConversations,
  TravelerConversation,
  EmailMessage,
  formatMessageDate,
} from '@/lib/sampleConversations';

// Types for the API response
interface ConversationUnderstanding {
  key_points: string[];
  resolved_issues: string[];
  open_issues: string[];
  promises_made: string[];
  concerns_raised: string[];
  relationship_tone: 'friendly' | 'formal' | 'frustrated' | 'neutral';
  current_status: string;
}

interface FollowUpResult {
  conversation_understanding: ConversationUnderstanding | null;
  message_approach?: string;
  should_follow_up: boolean;
  urgency: 'low' | 'medium' | 'high';
  channel: 'email' | 'phone';
  reasoning: string;
  message: {
    subject: string;
    body: string;
  } | null;
  context_usage?: string[];
}

// Missing items options
const MISSING_ITEMS_OPTIONS = [
  { id: 'passport', label: 'Passport scan' },
  { id: 'medical', label: 'Medical form' },
  { id: 'emergency', label: 'Emergency contact' },
  { id: 'waiver', label: 'Signed waiver' },
  { id: 'dietary', label: 'Dietary preferences' },
];

// Map label to id for pre-filling from URL params
const labelToId: Record<string, string> = {
  'Passport scan': 'passport',
  'Medical form': 'medical',
  'Emergency contact': 'emergency',
  'Signed waiver': 'waiver',
  'Dietary preferences': 'dietary',
};

// Loading messages that rotate (reference Sugati)
const LOADING_MESSAGES = [
  'Connecting to Sugati...',
  'Loading traveler profile from Salesforce...',
  'Checking communication history in Sugati...',
  'Analyzing conversation thread...',
  'Identifying key discussion points...',
  'Evaluating urgency based on departure date...',
  'Determining optimal approach...',
  'Generating context-aware message...',
];

function FollowUpForm() {
  const searchParams = useSearchParams();

  // Check if coming from digest
  const fromDigest = searchParams.get('from') === 'digest';

  // Conversation state
  const [selectedConversation, setSelectedConversation] = useState<TravelerConversation | null>(null);
  const [showConversationHistory, setShowConversationHistory] = useState(true);

  // Form state
  const [travelerName, setTravelerName] = useState('');
  const [email, setEmail] = useState('');
  const [daysUntilDeparture, setDaysUntilDeparture] = useState('');
  const [previousFollowUps, setPreviousFollowUps] = useState('0');
  const [missingItems, setMissingItems] = useState<string[]>([]);
  const [additionalNotes, setAdditionalNotes] = useState('');

  // UI state
  const [isLoading, setIsLoading] = useState(false);
  const [loadingMessageIndex, setLoadingMessageIndex] = useState(0);
  const [result, setResult] = useState<FollowUpResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [showCapabilities, setShowCapabilities] = useState(false);

  // Note: In production, this would come from API response
  // For now, using sample data (isLive = false)
  const isLiveData = false;

  // Rotate loading messages
  useEffect(() => {
    if (!isLoading) return;

    const interval = setInterval(() => {
      setLoadingMessageIndex((prev) => (prev + 1) % LOADING_MESSAGES.length);
    }, 2000);

    return () => clearInterval(interval);
  }, [isLoading]);

  // Handle conversation selection
  const handleConversationSelect = (travelerId: string) => {
    if (!travelerId) {
      setSelectedConversation(null);
      // Clear form
      setTravelerName('');
      setEmail('');
      setDaysUntilDeparture('');
      setPreviousFollowUps('0');
      setMissingItems([]);
      setAdditionalNotes('');
      setResult(null);
      return;
    }

    const conversation = sampleConversations.find((c) => c.travelerId === travelerId);
    if (conversation) {
      setSelectedConversation(conversation);
      // Pre-fill form from conversation
      setTravelerName(conversation.travelerName);
      setEmail(conversation.travelerEmail);
      setDaysUntilDeparture(conversation.daysUntilDeparture.toString());

      // Count outbound messages as previous follow-ups
      const outboundCount = conversation.thread.filter((m) => m.direction === 'outbound').length;
      setPreviousFollowUps(outboundCount >= 3 ? '3+' : outboundCount.toString());

      // Convert missing items to IDs
      const missingIds = conversation.missingItems
        .map((item) => labelToId[item] || item.toLowerCase().replace(/\s+/g, '_'))
        .filter(Boolean);
      setMissingItems(missingIds);

      setAdditionalNotes(conversation.notes || '');
      setResult(null);
    }
  };

  // Generate follow-up function
  const generateFollowUp = useCallback(async (
    name: string,
    emailAddr: string,
    days: string,
    contacts: string,
    missing: string[],
    notes: string,
    conversationHistory?: EmailMessage[],
    isVip?: boolean,
    previousTrips?: number
  ) => {
    setIsLoading(true);
    setLoadingMessageIndex(0);
    setError(null);
    setResult(null);

    try {
      const response = await fetch('/api/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          travelerName: name,
          email: emailAddr,
          daysUntilDeparture: parseInt(days),
          previousFollowUps: contacts,
          missingItems: missing.map(
            (id) => MISSING_ITEMS_OPTIONS.find((item) => item.id === id)?.label
          ),
          additionalNotes: notes,
          conversationHistory,
          isVip,
          previousTrips,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to generate follow-up');
      }

      const data = await response.json();
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Something went wrong');
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Pre-fill form from URL params and auto-generate
  useEffect(() => {
    const name = searchParams.get('name');
    const emailParam = searchParams.get('email');
    const days = searchParams.get('days');
    const contacts = searchParams.get('contacts');
    const missing = searchParams.get('missing');
    const notes = searchParams.get('notes');

    if (name && emailParam && days) {
      // Pre-fill form
      setTravelerName(name);
      setEmail(emailParam);
      setDaysUntilDeparture(days);

      // Convert contacts to dropdown value
      const contactNum = parseInt(contacts || '0');
      if (contactNum >= 3) {
        setPreviousFollowUps('3+');
      } else {
        setPreviousFollowUps(contactNum.toString());
      }

      // Convert missing items labels to IDs
      if (missing) {
        const missingLabels = missing.split(',');
        const missingIds = missingLabels
          .map(label => labelToId[label.trim()])
          .filter(Boolean);
        setMissingItems(missingIds);
      }

      if (notes) {
        setAdditionalNotes(notes);
      }

      // Auto-generate if coming from digest and haven't already
      if (fromDigest && !hasAutoGenerated) {
        setHasAutoGenerated(true);
        const missingLabels = missing ? missing.split(',') : [];
        const missingIds = missingLabels
          .map(label => labelToId[label.trim()])
          .filter(Boolean);

        generateFollowUp(
          name,
          emailParam,
          days,
          contactNum >= 3 ? '3+' : contactNum.toString(),
          missingIds,
          notes || ''
        );
      }
    }
  }, [searchParams, fromDigest, hasAutoGenerated, generateFollowUp]);

  // Handle checkbox changes
  const handleMissingItemChange = (itemId: string) => {
    setMissingItems((prev) =>
      prev.includes(itemId)
        ? prev.filter((id) => id !== itemId)
        : [...prev, itemId]
    );
  };

  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    generateFollowUp(
      travelerName,
      email,
      daysUntilDeparture,
      previousFollowUps,
      missingItems,
      additionalNotes,
      selectedConversation?.thread,
      selectedConversation?.isVip,
      selectedConversation?.previousTrips
    );
  };

  // Copy message to clipboard
  const copyToClipboard = async () => {
    if (result?.message) {
      const textToCopy = `Subject: ${result.message.subject}\n\n${result.message.body}`;
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  // Get urgency details
  const getUrgencyDetails = (urgency: string) => {
    switch (urgency) {
      case 'high':
        return {
          color: 'bg-red-100 text-red-700 border-red-200',
          icon: '🔴',
          explanation: 'Immediate action recommended',
        };
      case 'medium':
        return {
          color: 'bg-amber-100 text-amber-700 border-amber-200',
          icon: '🟡',
          explanation: 'Should address this week',
        };
      default:
        return {
          color: 'bg-gray-100 text-gray-700 border-gray-200',
          icon: '⚪',
          explanation: 'Can wait, but keep monitoring',
        };
    }
  };

  // Get contact count description
  const getContactDescription = () => {
    const count = previousFollowUps === '3+' ? 3 : parseInt(previousFollowUps);
    if (count === 0) return 'First contact — warm and welcoming tone';
    if (count === 1) return 'Second contact — friendly reminder tone';
    if (count === 2) return 'Third contact — more direct but still warm';
    return 'Multiple contacts — firm but understanding tone';
  };

  // Get tone badge color
  const getToneBadgeColor = (tone: string) => {
    switch (tone) {
      case 'friendly':
        return 'bg-green-100 text-green-700';
      case 'frustrated':
        return 'bg-red-100 text-red-700';
      case 'formal':
        return 'bg-blue-100 text-blue-700';
      default:
        return 'bg-gray-100 text-gray-700';
    }
  };

  const urgencyDetails = result ? getUrgencyDetails(result.urgency) : null;

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Header */}
      <header className="bg-white border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Link href="/" className="text-xl font-bold text-gray-900 hover:text-blue-600 transition-colors">GeoEx</Link>
              <span className="text-gray-300">|</span>
              <span className="text-gray-500">Follow-Up Agent</span>
            </div>
            <nav className="flex items-center gap-4">
              <Link
                href="/digest"
                className="text-sm text-gray-600 hover:text-gray-900 transition-colors"
              >
                Digest
              </Link>
              <Link
                href="/interpret"
                className="text-sm text-gray-600 hover:text-gray-900 transition-colors"
              >
                Interpret
              </Link>
              <Link
                href="/anomalies"
                className="text-sm text-gray-600 hover:text-gray-900 transition-colors"
              >
                Anomalies
              </Link>
            </nav>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 py-8 space-y-6 flex-1">
        {/* Data Source Indicator */}
        <div className="flex justify-end">
          <DataSourceIndicator isLive={isLiveData} />
        </div>

        {/* Back to Digest Banner (when coming from digest) */}
        {fromDigest && (
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span className="text-blue-600">📋</span>
              <span className="text-blue-800">
                Viewing details for <strong>{travelerName}</strong>
              </span>
            </div>
            <Link
              href="/digest"
              className="text-sm font-medium text-blue-600 hover:text-blue-800"
            >
              ← Return to Digest
            </Link>
          </div>
        )}

        {/* Conversation Selector */}
        {!fromDigest && (
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <span className="text-lg">💬</span>
                <h2 className="text-lg font-semibold text-gray-900">Load Conversation</h2>
              </div>
              <span className="text-xs text-gray-400">Demo: Select a sample conversation</span>
            </div>
            <select
              value={selectedConversation?.travelerId || ''}
              onChange={(e) => handleConversationSelect(e.target.value)}
              className="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white text-gray-900"
            >
              <option value="">— Select a traveler with conversation history —</option>
              {sampleConversations.map((conv) => (
                <option key={conv.travelerId} value={conv.travelerId}>
                  {conv.travelerName} — {conv.tripName} ({conv.thread.length} messages, {conv.missingItems.join(', ') || 'complete'})
                </option>
              ))}
            </select>
            {selectedConversation && (
              <div className="mt-3 flex flex-wrap gap-2">
                {selectedConversation.isVip && (
                  <span className="inline-flex items-center gap-1 px-2 py-1 bg-amber-100 text-amber-700 text-xs font-medium rounded-full">
                    ⭐ VIP
                  </span>
                )}
                {selectedConversation.previousTrips && selectedConversation.previousTrips > 0 && (
                  <span className="inline-flex items-center gap-1 px-2 py-1 bg-purple-100 text-purple-700 text-xs font-medium rounded-full">
                    🔄 {selectedConversation.previousTrips} previous trips
                  </span>
                )}
                <span className="inline-flex items-center gap-1 px-2 py-1 bg-gray-100 text-gray-700 text-xs font-medium rounded-full">
                  📅 {selectedConversation.daysSinceLastMessage} days since last message
                </span>
                <span className="inline-flex items-center gap-1 px-2 py-1 bg-gray-100 text-gray-700 text-xs font-medium rounded-full">
                  {selectedConversation.lastMessageDirection === 'inbound' ? '📥 Traveler' : '📤 GeoEx'} sent last
                </span>
              </div>
            )}
          </div>
        )}

        {/* Conversation History Panel */}
        {selectedConversation && selectedConversation.thread.length > 0 && (
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
            <button
              onClick={() => setShowConversationHistory(!showConversationHistory)}
              className="w-full px-6 py-4 flex items-center justify-between bg-gray-50 hover:bg-gray-100 transition-colors border-b border-gray-200"
            >
              <div className="flex items-center gap-3">
                <span className="text-lg">📧</span>
                <span className="font-medium text-gray-900">
                  Conversation History ({selectedConversation.thread.length} messages)
                </span>
              </div>
              <svg
                className={`w-5 h-5 text-gray-400 transition-transform ${showConversationHistory ? 'rotate-180' : ''}`}
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            </button>

            {showConversationHistory && (
              <div className="p-6 space-y-4 max-h-96 overflow-y-auto">
                {selectedConversation.thread.map((msg, index) => (
                  <div
                    key={index}
                    className={`p-4 rounded-lg ${
                      msg.direction === 'outbound'
                        ? 'bg-blue-50 border border-blue-100 ml-8'
                        : 'bg-gray-50 border border-gray-200 mr-8'
                    }`}
                  >
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-sm">
                        {msg.direction === 'outbound' ? '📤' : '📥'}
                      </span>
                      <span className={`text-xs font-medium px-2 py-0.5 rounded ${
                        msg.direction === 'outbound'
                          ? 'bg-blue-100 text-blue-700'
                          : 'bg-gray-200 text-gray-700'
                      }`}>
                        {msg.direction === 'outbound' ? 'GeoEx' : 'Traveler'}
                      </span>
                      <span className="text-xs text-gray-400">
                        {formatMessageDate(msg.date)}
                      </span>
                    </div>
                    <p className="text-sm font-medium text-gray-900 mb-1">
                      {msg.subject}
                    </p>
                    <p className="text-sm text-gray-600 whitespace-pre-wrap">
                      {msg.body}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* AI Capabilities Card (Collapsible) */}
        {!fromDigest && !selectedConversation && (
          <div className="border border-dashed border-gray-300 rounded-lg overflow-hidden">
            <button
              onClick={() => setShowCapabilities(!showCapabilities)}
              className="w-full px-4 py-3 flex items-center justify-between bg-gray-50 hover:bg-gray-100 transition-colors"
            >
              <span className="text-sm text-gray-600 flex items-center gap-2">
                <span>🧠</span>
                What this AI does
              </span>
              <span className="text-xs text-gray-400 flex items-center gap-1">
                {showCapabilities ? 'Hide' : 'Show'}
                <svg
                  className={`w-4 h-4 transition-transform ${showCapabilities ? 'rotate-180' : ''}`}
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                </svg>
              </span>
            </button>
            {showCapabilities && (
              <div className="px-4 py-4 bg-white border-t border-gray-200">
                <p className="text-sm text-gray-600 mb-3">
                  Enter traveler details and the AI will:
                </p>
                <ul className="space-y-2 text-sm">
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-0.5">✓</span>
                    <span className="text-gray-700">Analyze the full conversation history</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-0.5">✓</span>
                    <span className="text-gray-700">Identify key points, concerns, and promises made</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-0.5">✓</span>
                    <span className="text-gray-700">Decide if follow-up is needed right now</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-0.5">✓</span>
                    <span className="text-gray-700">Generate a context-aware message that references past exchanges</span>
                  </li>
                </ul>
              </div>
            )}
          </div>
        )}

        {/* Form Card */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Traveler Name & Email Row */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label
                  htmlFor="travelerName"
                  className="block text-sm font-medium text-gray-700 mb-1"
                >
                  Traveler Name
                </label>
                <input
                  type="text"
                  id="travelerName"
                  value={travelerName}
                  onChange={(e) => setTravelerName(e.target.value)}
                  placeholder="Sarah Chen"
                  required
                  className="w-full px-3 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label
                  htmlFor="email"
                  className="block text-sm font-medium text-gray-700 mb-1"
                >
                  Email
                </label>
                <input
                  type="email"
                  id="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="sarah@example.com"
                  required
                  className="w-full px-3 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
            </div>

            {/* Days & Previous Follow-ups Row */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label
                  htmlFor="daysUntilDeparture"
                  className="block text-sm font-medium text-gray-700 mb-1"
                >
                  Days Until Departure
                </label>
                <input
                  type="number"
                  id="daysUntilDeparture"
                  value={daysUntilDeparture}
                  onChange={(e) => setDaysUntilDeparture(e.target.value)}
                  placeholder="14"
                  min="0"
                  required
                  className="w-full px-3 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
              </div>
              <div>
                <label
                  htmlFor="previousFollowUps"
                  className="block text-sm font-medium text-gray-700 mb-1"
                >
                  Previous Follow-Ups Sent
                </label>
                <select
                  id="previousFollowUps"
                  value={previousFollowUps}
                  onChange={(e) => setPreviousFollowUps(e.target.value)}
                  className="w-full px-3 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white"
                >
                  <option value="0">0</option>
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3+">3+</option>
                </select>
              </div>
            </div>

            {/* Missing Items */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-3">
                Missing Items
              </label>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                {MISSING_ITEMS_OPTIONS.map((item) => (
                  <label
                    key={item.id}
                    className={`flex items-center gap-2 p-3 rounded-lg border cursor-pointer transition-colors ${
                      missingItems.includes(item.id)
                        ? 'bg-blue-50 border-blue-300'
                        : 'bg-white border-gray-200 hover:bg-gray-50'
                    }`}
                  >
                    <input
                      type="checkbox"
                      checked={missingItems.includes(item.id)}
                      onChange={() => handleMissingItemChange(item.id)}
                      className="rounded text-blue-600 focus:ring-blue-500"
                    />
                    <span className="text-sm text-gray-700">{item.label}</span>
                  </label>
                ))}
              </div>
            </div>

            {/* Additional Notes */}
            <div>
              <label
                htmlFor="additionalNotes"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Additional Notes
              </label>
              <textarea
                id="additionalNotes"
                value={additionalNotes}
                onChange={(e) => setAdditionalNotes(e.target.value)}
                placeholder="First-time GeoEx traveler, going to Patagonia. Mentioned she's been very busy at work..."
                rows={3}
                className="w-full px-3 py-2 rounded-lg border border-gray-300 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 resize-none"
              />
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              disabled={isLoading}
              className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 text-white font-medium py-3 px-4 rounded-lg transition-colors flex flex-col items-center justify-center gap-1"
            >
              {isLoading ? (
                <>
                  <div className="flex items-center gap-2">
                    <svg
                      className="animate-spin h-5 w-5"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                    >
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                      />
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
                      />
                    </svg>
                    <span>Generating recommendation...</span>
                  </div>
                  <span className="text-blue-200 text-sm">
                    {LOADING_MESSAGES[loadingMessageIndex]}
                  </span>
                </>
              ) : (
                selectedConversation
                  ? 'Generate Context-Aware Follow-Up'
                  : fromDigest && result ? 'Regenerate Follow-Up' : 'Generate Follow-Up'
              )}
            </button>
          </form>
        </div>

        {/* Error Display */}
        {error && (
          <div className="bg-red-50 border border-red-200 rounded-xl p-4">
            <p className="text-red-700">{error}</p>
          </div>
        )}

        {/* Results */}
        {result && (
          <div className="space-y-4">
            {/* Conversation Understanding Card */}
            {result.conversation_understanding && (
              <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                <div className="bg-purple-50 border-b border-purple-100 px-6 py-4">
                  <div className="flex items-center gap-3">
                    <span className="text-2xl">🧠</span>
                    <h2 className="text-lg font-semibold text-purple-900">
                      What I understood from this conversation
                    </h2>
                  </div>
                </div>

                <div className="p-6 space-y-4">
                  {/* Current Status */}
                  <div className="bg-gray-50 rounded-lg p-4">
                    <p className="text-sm text-gray-600 mb-1">Current Status</p>
                    <p className="text-gray-900 font-medium">{result.conversation_understanding.current_status}</p>
                  </div>

                  {/* Relationship Tone */}
                  <div className="flex items-center gap-2">
                    <span className="text-sm text-gray-600">Relationship tone:</span>
                    <span className={`px-2 py-1 text-xs font-medium rounded-full ${getToneBadgeColor(result.conversation_understanding.relationship_tone)}`}>
                      {result.conversation_understanding.relationship_tone}
                    </span>
                  </div>

                  {/* Key Points */}
                  {result.conversation_understanding.key_points.length > 0 && (
                    <div>
                      <p className="text-sm font-medium text-gray-700 mb-2">Key Points</p>
                      <ul className="space-y-1">
                        {result.conversation_understanding.key_points.map((point, i) => (
                          <li key={i} className="flex items-start gap-2 text-sm text-gray-600">
                            <span className="text-gray-400 mt-0.5">•</span>
                            {point}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {/* Resolved Issues */}
                    {result.conversation_understanding.resolved_issues.length > 0 && (
                      <div className="bg-green-50 rounded-lg p-3">
                        <p className="text-xs font-medium text-green-700 mb-2 flex items-center gap-1">
                          <span>✅</span> Resolved
                        </p>
                        <ul className="space-y-1">
                          {result.conversation_understanding.resolved_issues.map((issue, i) => (
                            <li key={i} className="text-sm text-green-800">{issue}</li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Open Issues */}
                    {result.conversation_understanding.open_issues.length > 0 && (
                      <div className="bg-amber-50 rounded-lg p-3">
                        <p className="text-xs font-medium text-amber-700 mb-2 flex items-center gap-1">
                          <span>⏳</span> Still Pending
                        </p>
                        <ul className="space-y-1">
                          {result.conversation_understanding.open_issues.map((issue, i) => (
                            <li key={i} className="text-sm text-amber-800">{issue}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>

                  {/* Promises Made */}
                  {result.conversation_understanding.promises_made.length > 0 && (
                    <div className="bg-blue-50 rounded-lg p-3">
                      <p className="text-xs font-medium text-blue-700 mb-2 flex items-center gap-1">
                        <span>🤝</span> Commitments Made
                      </p>
                      <ul className="space-y-1">
                        {result.conversation_understanding.promises_made.map((promise, i) => (
                          <li key={i} className="text-sm text-blue-800">{promise}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Concerns Raised */}
                  {result.conversation_understanding.concerns_raised.length > 0 && (
                    <div className="bg-orange-50 rounded-lg p-3">
                      <p className="text-xs font-medium text-orange-700 mb-2 flex items-center gap-1">
                        <span>⚠️</span> Traveler Concerns
                      </p>
                      <ul className="space-y-1">
                        {result.conversation_understanding.concerns_raised.map((concern, i) => (
                          <li key={i} className="text-sm text-orange-800">{concern}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Message Approach */}
                  {result.message_approach && (
                    <div className="border-t border-gray-100 pt-4 mt-4">
                      <p className="text-sm font-medium text-gray-700 mb-1">My approach for this message</p>
                      <p className="text-sm text-gray-600 italic">&ldquo;{result.message_approach}&rdquo;</p>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Decision Card - Enhanced */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              {/* Header with decision */}
              <div className={`px-6 py-4 ${result.should_follow_up ? 'bg-green-50 border-b border-green-100' : 'bg-gray-50 border-b border-gray-100'}`}>
                <div className="flex items-center gap-3">
                  <span className="text-2xl">{result.should_follow_up ? '✅' : '⏸️'}</span>
                  <div>
                    <h2 className="text-lg font-semibold text-gray-900">
                      {result.should_follow_up ? 'Follow Up Recommended' : 'No Follow-Up Needed'}
                    </h2>
                  </div>
                </div>
              </div>

              {/* Decision details */}
              <div className="p-6 space-y-4">
                {/* Channel */}
                <div className="flex items-start gap-4">
                  <div className="flex-shrink-0 w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
                    {result.channel === 'email' ? (
                      <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                      </svg>
                    ) : (
                      <svg className="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                      </svg>
                    )}
                  </div>
                  <div>
                    <p className="font-medium text-gray-900">
                      {result.channel === 'email' ? 'Email' : 'Phone Call'}
                    </p>
                    <p className="text-sm text-gray-500">
                      {result.channel === 'email'
                        ? 'Email is appropriate for this situation'
                        : 'Phone call recommended — email may not be effective'}
                    </p>
                  </div>
                </div>

                {/* Urgency */}
                <div className="flex items-start gap-4">
                  <div className={`flex-shrink-0 w-10 h-10 rounded-lg flex items-center justify-center ${
                    result.urgency === 'high' ? 'bg-red-100' :
                    result.urgency === 'medium' ? 'bg-amber-100' : 'bg-gray-100'
                  }`}>
                    <span className="text-lg">{urgencyDetails?.icon}</span>
                  </div>
                  <div>
                    <p className="font-medium text-gray-900">
                      {result.urgency.charAt(0).toUpperCase() + result.urgency.slice(1)} Urgency
                    </p>
                    <p className="text-sm text-gray-500">
                      {urgencyDetails?.explanation}
                    </p>
                  </div>
                </div>

                {/* Tone */}
                <div className="flex items-start gap-4">
                  <div className="flex-shrink-0 w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center">
                    <span className="text-lg">✍️</span>
                  </div>
                  <div>
                    <p className="font-medium text-gray-900">Tone Adjustment</p>
                    <p className="text-sm text-gray-500">
                      {getContactDescription()}
                    </p>
                  </div>
                </div>
              </div>

              {/* AI Reasoning - More prominent */}
              <div className="px-6 py-4 bg-blue-50 border-t border-blue-100">
                <div className="flex items-start gap-3">
                  <span className="text-xl">🧠</span>
                  <div>
                    <h3 className="text-sm font-semibold text-blue-900 mb-1">
                      How I decided this
                    </h3>
                    <p className="text-sm text-blue-800 italic">
                      &ldquo;{result.reasoning}&rdquo;
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Message Card */}
            {result.message && (
              <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                <div className="bg-gray-50 border-b border-gray-200 px-6 py-4">
                  <h3 className="text-sm font-medium text-gray-500 mb-1">
                    Subject
                  </h3>
                  <p className="text-gray-900 font-medium">
                    {result.message.subject}
                  </p>
                </div>
                <div className="px-6 py-4">
                  <h3 className="text-sm font-medium text-gray-500 mb-2">
                    Message
                  </h3>
                  <div className="prose prose-sm max-w-none text-gray-700 whitespace-pre-wrap">
                    {result.message.body}
                  </div>
                </div>

                {/* Context Usage */}
                {result.context_usage && result.context_usage.length > 0 && (
                  <div className="px-6 py-4 bg-purple-50 border-t border-purple-100">
                    <h3 className="text-sm font-semibold text-purple-900 mb-2 flex items-center gap-2">
                      <span>🔗</span>
                      How this message uses conversation context
                    </h3>
                    <ul className="space-y-1">
                      {result.context_usage.map((usage, i) => (
                        <li key={i} className="text-sm text-purple-800 flex items-start gap-2">
                          <span className="text-purple-400 mt-0.5">•</span>
                          {usage}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                <div className="bg-gray-50 border-t border-gray-200 px-6 py-4">
                  <button
                    onClick={copyToClipboard}
                    className="inline-flex items-center gap-2 bg-white border border-gray-300 hover:bg-gray-50 text-gray-700 font-medium py-2 px-4 rounded-lg transition-colors"
                  >
                    {copied ? (
                      <>
                        <svg
                          className="w-4 h-4 text-green-600"
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={2}
                            d="M5 13l4 4L19 7"
                          />
                        </svg>
                        Copied!
                      </>
                    ) : (
                      <>
                        <svg
                          className="w-4 h-4"
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={2}
                            d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                          />
                        </svg>
                        Copy Message
                      </>
                    )}
                  </button>
                </div>
              </div>
            )}
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-200 bg-white mt-auto">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <p className="text-center text-xs text-gray-400">
            Powered by AI · Recommendations are suggestions — use your judgment for final decisions
          </p>
        </div>
      </footer>
    </div>
  );
}

export default function FollowUpPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-gray-500">Loading...</div>
      </div>
    }>
      <FollowUpForm />
    </Suspense>
  );
}
